### ISSUE TITLE
Menu alignment is off

### ISSUE THREAD

**Issue by infotexture** [oxygenxml/oxygen-resources-converter#26]
The **Tools > Batch Converter** menu item does not align with the other text-only entries in the **Tools** menu.

The command appears in the area normally reserved for icons.

**Comment by raducoravu** [comment]
Thanks @infotexture 
@DunaMariusCosmin  This is probably only for Mac OSX. We need to add an empty icon to the menu to properly align it, that's how we handle this in the main application code.

**Comment by infotexture** [comment]
👍 The changes in ff32d35 solve the problem.

The menu item is properly aligned with add-on v1.0.8.
