### ISSUE TITLE
A couple more UI changes

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-converter#27]
Feedback from our QA:

The label "Add Input Files" should be changed to "Input Files".
The "Add folders" and "Add files" buttons should have "..." appended to them because they open dialogs.

**Comment by raducoravu** [comment]
Also the output text field and the table containing resources should be left aligned, without any extra padding to the left.

**Comment by DunaMariusCosmin** [comment]
Edited the UI text in : fecd23a5af50f52da6829fe648303133284facb7
