### ISSUE TITLE
Convert HTML to Docbook

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-converter#28]
Only for Oxygen 20 or newer.

**Comment by raducoravu** [comment]
Maybe also add some separators in the Tools conversions menu to separate various conversion categories, conversions to DITA, conversions to Docbook, the XML to JSON and viceversa conversion.

**Comment by DunaMariusCosmin** [comment]
Fixed in: ea6dfae04b744340bd03fc914c2647a56ec41bc9
