### ISSUE TITLE
"Wrong" file encoding throws path not found error

### ISSUE THREAD

**Issue by xephon2** [oxygenxml/oxygen-resources-converter#30]
If the file is encoded with UTF-8 (no BOM) or ANSI or ISO 8859-1, the batch converter cannot find the file and throws:

```
Das System kann den angegebenen Pfad nicht finden (System cannot find path)
```

Tested with:

* <oXygen/> XML Editor 19.1, build 2017121318
* Batch Converter 1.1.1
* JSON2XML conversion

**Comment by raducoravu** [comment]
@xephon2 could you also attached a zipped JSON file? I tried this with a JSON file containing some Japanese characters in the values but it seems to work for me.

**Comment by xephon2** [comment]
[strings.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/1723376/strings.zip)
