### ISSUE TITLE
Graceful handling of conversion problems and logging

### ISSUE THREAD

**Issue by nosaj3** [oxygenxml/oxygen-resources-converter#32]
This is a great add-on. One thing I think would be helpful is if it was able to gracefully exit from failed conversions. I'm sure that on some of the content I have tried this with there are fundamental problems I need to address before running the conversion. What I am seeing is the conversion process gets stuck, nothing is logged, and it just runs indefinitely until I click the cancel button. 

I'm pretty sure I can just throw my content in a  map and see what sort of validation errors pop up but it would be nice if I didn't need to use this intermediary step.

I've only tried the Markdown to DITA conversion btw.

**Comment by raducoravu** [comment]
Thanks for the kind words.
If you have these problems with the latest add-on, maybe you can attach some sample Markdown files for which the conversion never finishes and we'll take a look at them.

**Comment by nosaj3** [comment]
Sure thing. When I get a chance, I'll cobble together a sample and attach it here.

**Comment by raducoravu** [comment]
@nosaj3 Sure, I will reopen this issue when you post extra samples on it.

**Comment by raducoravu** [comment]
Thanks @nosaj3, I can reproduce the problem and we'll look into this.

**Comment by DunaMariusCosmin** [comment]
The new release (1.1.8) contains this fix.
Thanks you for this report.
