### ISSUE TITLE
Conversion of HTML to DITA ignores content below the 2nd level of content hierarchy

### ISSUE THREAD

**Issue by nosaj3** [oxygenxml/oxygen-resources-converter#33]
If you use the conversion tool to convert HTML to DITA, the result is a single topic based on the highest heading level with any subsequent child headings as <section> elements. However, if those child headings contain any children headings, those children headings are ignored and any content grouped under those children are ignored. 

In other words:

- h1 - processed as topic
all content under h1 processed
- h2 - processed as section
all content under h2 processed 
- h3 - ignored
all content under h3 ignored

Ideally, all child headers would be transformed as topics instead. I don't know how reasonable it is to expect this operation to handle this. However, the current result is content just disappears without a trace. Even a report that states something along the lines of "your content hierarchy is too deep for this to work on all your content" would be better than how it currently works.

**Comment by DunaMariusCosmin** [comment]
Thanks @nosaj3 for report.
 We will release the new version of Oxygen XML Editor in a couple of weeks and will try to resolve this problem in this version.

**Comment by DunaMariusCosmin** [comment]
The new version of Oxygen XML Editor ([20.1](https://www.oxygenxml.com/xml_editor/whatisnew20.1.html)) was released. The problem was resolved in this version.
