### ISSUE TITLE
<p> tags error in the generated dita document

### ISSUE THREAD

**Issue by puniththota** [oxygenxml/oxygen-resources-converter#37]
For the dita document generated from a word document, if there is content/text before a header/heading, this text is converted to a p tag in the dita document. This p tag appears outside of the main tags and therefore is being flagged as an error. 
[WordDocument.docx](https://github.com/oxygenxml/oxygen-resources-converter/files/4981990/WordDocument.docx)
[WordDocumentDitaOutput.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/4981991/WordDocumentDitaOutput.zip)

**Comment by raducoravu** [comment]
Thanks for registering an issue, we'll try to find some time to look into this. In such cases you can perform some manual post process and we'll try to look on our side to fix this behavior.

**Comment by DunaMariusCosmin** [comment]
We added a fix for this problem, but this will be available in version 23.1 of Oxygen because it required some changes in the main application.

**Comment by DunaMariusCosmin** [comment]
Hi,
I just wanted to let you know that Oxygen 23.1 is out now and it contains a fix for the issue you reported.
