### ISSUE TITLE
Single quote in Excel tab name leads to invalid DITA

### ISSUE THREAD

**Issue by oughnic** [oxygenxml/oxygen-resources-converter#51]
When converting a spreadsheet with a single quote in the tab name (e.g "Parkinson's Disease") the table ID is closed by the single quote.

Suggest replacing single quote with a different character in the table ID

**Comment by DunaMariusCosmin** [comment]
Hi, 
Thank you for reporting this issue. I reproduced the problem and I registered an internal issue for this. We will fix it in the next version of the add-on.

Regards,
Cosmin

**Comment by DunaMariusCosmin** [comment]
Hi,
I just wanted to let you know that version 3.1.0 is out now and it contains a fix for the problem you reported.
Regards,
Cosmin
