### ISSUE TITLE
Update Log4j to 2.18

### ISSUE THREAD

**Issue by reifsnid** [oxygenxml/oxygen-resources-converter#52]
Hi,

Just wondering if it would be possible to update the add-on to use log4j 2.18? 

My company's security team wants all log4j instances on company computers to use version 2.18 as previous versions have reported vulnerabilities. 

Thanks!

**Comment by DunaMariusCosmin** [comment]
Hi, 
The Batch Documents Converter add-on has no longer distributed Apache Log4j libraries starting with version 3.2.1. 
So I recommend you to update to the latest version if you use an older one.

Now the add-on is based on SLF4J and uses the logging framework that it finds in Oxygen.
The last version of Oxygen (24.1) has completely removed log4j  and now it users Logback.

Best regards,
Cosmin
