### ISSUE TITLE
Question: OpenAPI to DITA generates definition lists instead of tables

### ISSUE THREAD

**Issue by kirkilj** [oxygenxml/oxygen-resources-converter#53]
Can you help me understand why the OpenAPI to DITA converter generates nested &lt;dl>s instead of nested &lt;table>s? Where would this be customized if we wanted to alter it slightly?

**Comment by DunaMariusCosmin** [comment]
Hi, 
In version 25 of Oxygen, we will add some CSS that will present some of the dl elements as tables on the Author page and when these are published to Webhelp.

If you want to change them, you can create a refactoring operation that will process the DITA result. This xsl can be used for this: 
`<?xml version="1.0" encoding="UTF-8"?>

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    exclude-result-prefixes="xs"
    version="2.0">
    
    <xsl:template match="@* | node()">
        <xsl:copy>
            <xsl:apply-templates select="@* | node()"/>
        </xsl:copy>
    </xsl:template>
    
    
    <xsl:variable name="listsToConvert" 
        select="('openapi-parameter-properties', 'openapi-schema-values', 'openapi-link-fields-list',
        'openapi-link-parameters-list', 'openapi-mediaType-fields-list', 'openapi-securityScheme-properties',
        'openapi-specification-extensions')"/>
    
    <xsl:template match="dl[@outputclass = $listsToConvert]">
        <xsl:choose>
            <xsl:when test="parent::*[local-name() = 'dl' or local-name() = 'dd']">
                <p>
                <table>
                    <xsl:apply-templates select="@*"/>
                    <tgroup cols="2">
                        <tbody>
                            <xsl:apply-templates select="node()"/>
                        </tbody>
                    </tgroup>
                </table>
                </p>
            </xsl:when>
            <xsl:otherwise>
                
                <table>
                    <xsl:apply-templates select="@*"/>
                    <tgroup cols="2">
                        <tbody>
                            <xsl:apply-templates select="node()"/>
                        </tbody>
                    </tgroup>
                </table>
            </xsl:otherwise>
        </xsl:choose>
       
    </xsl:template>
    
    <xsl:template match="dl[@outputclass = $listsToConvert]/dlentry">
        
        <row>
            <xsl:apply-templates select="@* | node()"/>
        </row>
    </xsl:template>
    
    <xsl:template match="dl[@outputclass = $listsToConvert]/dlentry/*[local-name() = 'dd' or local-name() = 'dt']">
        
        <entry>
            <xsl:apply-templates select="@* | node()"/>
        </entry>
    </xsl:template>
</xsl:stylesheet>`
